- name: "Example playbook showing usage of cloudfront_invalidate module"
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: "Make an example invalidation request for two paths"
      cloudfront_invalidate:
        aws_access_key: "YOUR_AWS_ACCESS_KEY"
        aws_secret_key: "YOUR_AWS_SECRET_KEY"
        distribution_id: "YOUR_CLOUDFRONT_DIST_ID"
        path: "{{item}}"
      with_items:
        - "/js/*"
        - "archive.zip"
